when@dev:
    framework:
        mailer:
            envelope:
                recipients: ['%env(MAILER_DEBUG_EMAIL)%']
framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            # sender: 'matos@mmi-troyes.fr'
            sender: '%env(MAILER_SENDER)%'
        headers:
            From: '%env(MAILER_HEADER_FROM)%'
