vich_uploader:
    db_driver: orm

    mappings:
        equipment:
            uri_prefix: /images/equipment
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
